# Generated by Django 4.1.6 on 2023-02-17 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_projects_api_key_alter_projects_project_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='projects',
            name='api_key',
            field=models.UUIDField(default=uuid.UUID('c018611d-b06e-44ac-9576-544fd53935f0'), unique=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_id',
            field=models.UUIDField(default=uuid.UUID('57992ee2-aec4-11ed-b105-91795fc0162a'), primary_key=True, serialize=False),
        ),
    ]
